### ISSUE TITLE
colorlight 5a-75b failed to compile with --ethernet

### ISSUE THREAD

**Issue by stanleyseow** [litex-hub/litex-boards#216]
I'm able to compile ./colorlight_5a_75x.py --revision=8.0 and able to boot to the BIOS...
when I tried adding ethernet , it gives compilation errors.. 

**./colorlight_5a_75x.py --ethernet --cpu-type vexriscv**

Info: pin 'eth0_tx_data[0]$tr_io' constrained to Bel 'X0/Y26/PIOD'.
Info: pin 'eth0_tx_data[1]$tr_io' constrained to Bel 'X0/Y26/PIOC'.
Info: pin 'eth0_tx_data[2]$tr_io' constrained to Bel 'X0/Y35/PIOA'.
Info: pin 'eth0_tx_data[3]$tr_io' constrained to Bel 'X0/Y35/PIOB'.
Info: IOLOGIC component DELAYG connected to PIO Bel X0/Y26/PIOA
terminate called after throwing an instance of 'nextpnr_ecp5::assertion_failure'
  what():  Assertion failure: is_string (/home/travis/build/xobs/toolchain-nextpnr-ecp5/_builds/build_linux_x86_64/nextpnr/common/nextpnr.h:340)
build_colorlight_5a_75b.sh: line 4: 51857 Aborted                 (core dumped) nextpnr-ecp5 --json colorlight_5a_75b.json --lpf colorlight_5a_75b.lpf --textcfg colorlight_5a_75b.config --25k --package CABGA256 --speed 6 --timing-allow-fail --seed 1
Traceback (most recent call last):
  File "./colorlight_5a_75x.py", line 214, in <module>
    main()
  File "./colorlight_5a_75x.py", line 207, in main
    builder.build(**trellis_argdict(args), run=args.build)
  File "/home/stanley/litex/litex/soc/integration/builder.py", line 281, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/home/stanley/litex/litex/soc/integration/soc.py", line 1103, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/stanley/litex/litex/build/lattice/platform.py", line 41, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/stanley/litex/litex/build/lattice/trellis.py", line 245, in build
    _run_script(script)
  File "/home/stanley/litex/litex/build/lattice/trellis.py", line 174, in _run_script
    raise OSError("Error occured during Yosys/Nextpnr's script execution.")
OSError: Error occured during Yosys/Nextpnr's script execution.

**Comment by stanleyseow** [comment]
Sorry, was using an older toolchain, the latest from toolchain from here solved it  https://github.com/YosysHQ/fpga-toolchain/releases
