### ISSUE TITLE
kc705.py doesn't build with cpu-type set to None

### ISSUE THREAD

**Issue by jersey99** [litex-hub/litex-boards#89]
@enjoy-digital Looks like this  9d1443c1 in Litex repo

```
:~/software/litex/litex-boards/litex_boards/targets$ master$ python kc705.py --with-ethernet --cpu-type None
INFO:SoC:        __   _ __      _  __  
INFO:SoC:       / /  (_) /____ | |/_/  
INFO:SoC:      / /__/ / __/ -_)>  <    
INFO:SoC:     /____/_/\__/\__/_/|_|  
INFO:SoC:  Build your hardware, easily!
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Creating SoC... (2020-07-12 13:30:09)
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:FPGA device : xc7k325t-ffg900-2.
INFO:SoC:System clock: 125.00MHz.
INFO:SoCBusHandler:Creating Bus Handler...
INFO:SoCBusHandler:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoCBusHandler:Adding reserved Bus Regions...
INFO:SoCBusHandler:Bus Handler created.
INFO:SoCCSRHandler:Creating CSR Handler...
INFO:SoCCSRHandler:8-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging (Up to 32 Locations).
INFO:SoCCSRHandler:Adding reserved CSRs...
INFO:SoCCSRHandler:CSR Handler created.
INFO:SoCIRQHandler:Creating IRQ Handler...
INFO:SoCIRQHandler:IRQ Handler (up to 32 Locations).
INFO:SoCIRQHandler:Adding reserved IRQs...
INFO:SoCIRQHandler:IRQ Handler created.
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Initial SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoC:8-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging (Up to 32 Locations).
INFO:SoC:IRQ Handler (up to 32 Locations).
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCCSRHandler:ctrl CSR allocated at Location 0.
INFO:SoCBusHandler:io0 Region added at Origin: 0x00000000, Size: 0x100000000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:rom Region added at Origin: 0x00000000, Size: 0x00008000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:rom added as Bus Slave.
INFO:SoC:RAM rom added Origin: 0x00000000, Size: 0x00008000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:sram Region added at Origin: 0x01000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:sram added as Bus Slave.
INFO:SoC:RAM sram added Origin: 0x01000000, Size: 0x00002000, Mode: RW, Cached: True Linker: False.
INFO:SoCCSRHandler:identifier_mem CSR allocated at Location 1.
INFO:SoCCSRHandler:uart_phy CSR allocated at Location 2.
INFO:SoCCSRHandler:uart CSR allocated at Location 3.
INFO:SoCCSRHandler:timer0 CSR allocated at Location 4.
ERROR:SoCBusHandler:Region overlap between rom and csr:
ERROR:SoCBusHandler:Origin: 0x00000000, Size: 0x00008000, Mode: R, Cached: True Linker: False
ERROR:SoCBusHandler:Origin: 0x00000000, Size: 0x00010000, Mode: RW, Cached: False Linker: False
Traceback (most recent call last):
  File "kc705.py", line 113, in <module>
    main()
  File "kc705.py", line 104, in main
    soc = BaseSoC(with_ethernet=args.with_ethernet, **soc_sdram_argdict(args))
  File "kc705.py", line 55, in __init__
    **kwargs)
  File "/home/w/software/litex/litex/litex/soc/integration/soc_core.py", line 187, in __init__
    self.add_csr_bridge(self.mem_map["csr"])
  File "/home/w/software/litex/litex/litex/soc/integration/soc.py", line 752, in add_csr_bridge
    self.bus.add_slave("csr", self.csr_bridge.wishbone, csr_region)
  File "/home/w/software/litex/litex/litex/soc/integration/soc.py", line 333, in add_slave
    self.add_region(name, region)
  File "/home/w/software/litex/litex/litex/soc/integration/soc.py", line 207, in add_region
    raise
RuntimeError: No active exception to reraise
```

**Comment by enjoy-digital** [comment]
This has been fixed in LiteX.
